# Generated by Django 4.0.1 on 2022-07-18 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Binrequest',
        ),
    ]
