# Generated by Django 4.0.1 on 2022-07-18 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('binapp', '0002_delete_binrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Binrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.TextField()),
                ('location_latitude', models.CharField(max_length=20, null=True, unique=True)),
                ('location_longitude', models.CharField(max_length=20, null=True, unique=True)),
                ('date', models.DateField(auto_now=True)),
                ('approval_status', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
